all:
	rm -f index.txt
	ls -1 *.m4 >index.txt
	ls -1 *.m4 >>index.txt
	m4 -I../_m4 "node  .  .  .m4" >"node  .  .  .html"
	m4 -I../_m4 "node00.  .  .m4" >"node00.  .  .html"
	m4 -I../_m4 "node00.01.  .m4" >"node00.01.  .html"
	m4 -I../_m4 "node00.02.  .m4" >"node00.02.  .html"
	m4 -I../_m4 "node00.03.  .m4" >"node00.03.  .html"
	m4 -I../_m4 "node00.04.  .m4" >"node00.04.  .html"
	m4 -I../_m4 "node01.  .  .m4" >"node01.  .  .html"
	m4 -I../_m4 "node01.03.  .m4" >"node01.03.  .html"
	m4 -I../_m4 "node01.03.01.m4" >"node01.03.01.html"
