#define PRJ_VERSION		4
#define PRJ_REVISION	1
#define PRJ_BUILD		0
#define PRJ_NAME		"Hall2"
#define PRJ_VERS		PRJ_NAME" "NUM2STR(PRJ_VERSION)"."NUM2STR(PRJ_REVISION)"."NUM2STR(PRJ_BUILD)" for SoundFX © by Stefan Kost 1993-2000"
