#define PRJ_VERSION		4
#define PRJ_REVISION	3
#define PRJ_BUILD	97
#define PRJ_NAME		"SoundFX"
#define PRJ_VERS		PRJ_NAME" "NUM2STR(PRJ_VERSION)"."NUM2STR(PRJ_REVISION)"."NUM2STR(PRJ_BUILD)" "__AMIGADATE__" "VERS_BITS"/"VERS_PREC" for "_CPUNAME"/"_FPUNAME" © 1993-2004 by Stefan Kost"
