#define GUICmd(xs,ys) \
	ng.ng_LeftEdge		=xs+RunTime.scx[64];\
	ng.ng_TopEdge		=ys+RunTime.scy[2];\
	ng.ng_Width			=RunTime.scx[80];\
	ng.ng_Height		=RunTime.scy[11];\
	ng.ng_GadgetText	="_Go";\
	ng.ng_TextAttr		=RunTime.ScrFontB;\
	ng.ng_GadgetID		=0;\
	ng.ng_Flags			=PLACETEXT_IN;\
	ng.ng_VisualInfo	=RunTime.VisualInfo;\
	g=CreateGadget(BUTTON_KIND,g,&ng,GT_Underscore,'_',TAG_DONE);\
	ng.ng_LeftEdge		=xs+RunTime.scx[164];\
	ng.ng_GadgetText	="_Reset";\
	ng.ng_TextAttr		=RunTime.ScrFont;\
	ng.ng_GadgetID		=10;\
	g=CreateGadget(BUTTON_KIND,g,&ng,GT_Underscore,'_',TAG_DONE);

#define GUISrc(xs,ys,id1,str,id2,rmd) \
	ng.ng_LeftEdge		=xs+RunTime.scx[37];\
	ng.ng_TopEdge		=ys+RunTime.scy[2];\
	ng.ng_Width			=RunTime.scx[15];\
	ng.ng_TextAttr		=RunTime.SigFont;\
	ng.ng_GadgetText	=IMAGE_PopUp;\
	ng.ng_GadgetID		=1;\
	g=CreateGadget(BUTTON_KIND,g,&ng,TAG_DONE);\
	ng.ng_LeftEdge		=xs+RunTime.scx[53];\
	ng.ng_Width			=RunTime.scx[155];\
	ng.ng_TextAttr		=RunTime.ScrFont;\
	ng.ng_GadgetText	="";\
	ng.ng_GadgetID		=2;\
	g=CreateGadget(TEXT_KIND,g,&ng,GTTX_Border,TRUE,GTTX_Text,str,GTTX_CopyText,TRUE,TAG_DONE);\
	fxGadgets[id1]=g;\
	ng.ng_LeftEdge		=xs+RunTime.scx[214];\
	ng.ng_Width			=RunTime.scx[90];\
	ng.ng_GadgetText	="";\
	ng.ng_GadgetID		=13;\
	ng.ng_Flags			=PLACETEXT_LEFT;\
	g=CreateGadget(CYCLE_KIND,g,&ng,GTCY_Labels,RModeLabels,GTCY_Active,rmd,TAG_DONE);\
	fxGadgets[id2]=g;

#define GUIMod(xs,ys,id1,par1,id2,par2,id3,bshp,id4,id5,str,id6,bmod) \
	ng.ng_LeftEdge		=xs+RunTime.scx[37];\
	ng.ng_TopEdge		=ys+3+RunTime.scy[8];\
	ng.ng_Width			=RunTime.scx[69];\
	ng.ng_GadgetText	="Par";\
	ng.ng_GadgetID		=3;\
	ng.ng_Flags			=PLACETEXT_LEFT;\
	g=CreateGadget(STRING_KIND,g,&ng,GTST_MaxChars,15,GTST_String,par1,TAG_DONE);\
	fxGadgets[id1]=g;\
	ng.ng_LeftEdge		=xs+RunTime.scx[139];\
	ng.ng_GadgetText	="";\
	ng.ng_GadgetID		=4;\
	g=CreateGadget(STRING_KIND,g,&ng,GTST_MaxChars,15,GTST_String,par2,TAG_DONE);\
	fxGadgets[id2]=g;\
	ng.ng_LeftEdge		=xs+RunTime.scx[107];\
	ng.ng_Width			=RunTime.scx[31];\
	ng.ng_GadgetText	="<->";\
	ng.ng_GadgetID		=11;\
	ng.ng_Flags			=PLACETEXT_IN;\
	g=CreateGadget(BUTTON_KIND,g,&ng,TAG_DONE);\
	ng.ng_LeftEdge		=xs+RunTime.scx[214];\
	ng.ng_Width			=RunTime.scx[90];\
	ng.ng_GadgetText	="";\
	ng.ng_GadgetID		=6;\
	ng.ng_Flags			=PLACETEXT_LEFT;\
	g=CreateGadget(CYCLE_KIND,g,&ng,GTCY_Labels,BShapeLabels,GTCY_Active,bshp,TAG_DONE);\
	fxGadgets[id3]=g;\
	ng.ng_LeftEdge		=xs+RunTime.scx[37];\
	ng.ng_TopEdge		=ys+3+RunTime.scy[20];\
	ng.ng_Width			=RunTime.scx[15];\
	ng.ng_TextAttr		=RunTime.SigFont;\
	ng.ng_GadgetText	=IMAGE_PopUp;\
	ng.ng_GadgetID		=7;\
	ng.ng_Flags			=PLACETEXT_IN;\
	g=CreateGadget(BUTTON_KIND,g,&ng,TAG_DONE);\
	fxGadgets[id4]=g;\
	ng.ng_LeftEdge		=xs+RunTime.scx[53];\
	ng.ng_Width			=RunTime.scx[155];\
	ng.ng_TextAttr		=RunTime.ScrFont;\
	ng.ng_GadgetText	="";\
	ng.ng_GadgetID		=8;\
	g=CreateGadget(TEXT_KIND,g,&ng,GTTX_Border,TRUE,GTTX_Text,str,GTTX_CopyText,TRUE,TAG_DONE);\
	fxGadgets[id5]=g;\
	ng.ng_LeftEdge		=xs+RunTime.scx[214];\
	ng.ng_Width			=RunTime.scx[90];\
	ng.ng_GadgetText	="";\
	ng.ng_GadgetID		=9;\
	g=CreateGadget(CYCLE_KIND,g,&ng,GTCY_Labels,BModeLabels,GTCY_Active,bmod,TAG_DONE);\
	fxGadgets[id6]=g;
